language: node_js
sudo: false
dist: trusty
node_js:
- '8'
env:
  global:
    - HOST=127.0.0.1
    - PORT=8080
addons:
  ssh_known_hosts: meoup.pedrocamara.me
before_deploy:
- openssl aes-256-cbc -K $encrypted_b6f1eb337590_key -iv $encrypted_b6f1eb337590_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --exclude=".git" --exclude="node_modules" --quiet $TRAVIS_BUILD_DIR/ admin@meoup.pedrocamara.me:~/meoup-server && ssh admin@meoup.pedrocamara.me -t 'cd ~/meoup-server && npm i && pm2 restart meoup'
  on:
    branch: master
after_deploy:
- ssh-agent -k