language: generic
sudo: required
services:
  - docker
addons:
  ssh_known_hosts: meoup.pedrocamara.me
before_install:
- curl -L https://github.com/docker/machine/releases/download/v0.14.0/docker-machine-`uname -s`-`uname -m` -o docker-machine
- sudo mv docker-machine /usr/local/bin/.
- sudo chmod +x /usr/local/bin/docker-machine

script:
- docker build .

before_deploy:
- openssl aes-256-cbc -K $encrypted_b6f1eb337590_key -iv $encrypted_b6f1eb337590_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- docker-machine create --driver generic --generic-ip-address=meoup.pedrocamara.me remote
- eval $(docker-machine env remote)
deploy:
  provider: script
  skip_cleanup: true
  script: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d --build
  on:
    branch: master
after_deploy:
- docker-machine rm -y remote
- ssh-agent -k