version: '3'
services:
  node:
    image: pedrock/meoup
    build: .
    links:
      - "redis"
    expose:
      - "8080"
    environment:
      VIRTUAL_HOST: meoup.pedrocamara.me
      WEB_PORTS: "8080"
      LETSENCRYPT_HOST: meoup.pedrocamara.me
      LETSENCRYPT_EMAIL: camara-pedro@hotmail.com

  redis:
    image: redis:alpine
    volumes: 
        - redis-data:/data

  nginx-proxy:
    image: jwilder/nginx-proxy
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx:/etc/nginx/certs"
      - "nginx:/etc/nginx/vhost.d"
      - "nginx:/usr/share/nginx/html"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes:
      - "nginx:/etc/nginx/certs"
      - "nginx:/etc/nginx/vhost.d"
      - "nginx:/usr/share/nginx/html"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

volumes:
  redis-data:
    driver: local
  nginx:
    driver: local