// flow-typed signature: 26e1d18f395e9605f6cb2ad8a5ffb9bd
// flow-typed version: <<STUB>>/@nuxtjs/component-cache_v^1.0.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nuxtjs/component-cache'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nuxtjs/component-cache' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@nuxtjs/component-cache/index' {
  declare module.exports: $Exports<'@nuxtjs/component-cache'>;
}
declare module '@nuxtjs/component-cache/index.js' {
  declare module.exports: $Exports<'@nuxtjs/component-cache'>;
}
