// flow-typed signature: d01cdf66c24f504d3ad181678edef265
// flow-typed version: <<STUB>>/@nuxtjs/pwa_v^0.2.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@nuxtjs/pwa'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@nuxtjs/pwa' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module '@nuxtjs/pwa/index' {
  declare module.exports: $Exports<'@nuxtjs/pwa'>;
}
declare module '@nuxtjs/pwa/index.js' {
  declare module.exports: $Exports<'@nuxtjs/pwa'>;
}
