// flow-typed signature: c3d03a5f4393a258973ee3cb9bcc7024
// flow-typed version: <<STUB>>/argon2_v^0.16.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'argon2'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'argon2' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'argon2/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'argon2/index' {
  declare module.exports: $Exports<'argon2'>;
}
declare module 'argon2/index.js' {
  declare module.exports: $Exports<'argon2'>;
}
declare module 'argon2/test.js' {
  declare module.exports: $Exports<'argon2/test'>;
}
