// flow-typed signature: e3f1ff5381c3772461ee6777ca0ed4a9
// flow-typed version: <<STUB>>/backpack-core_v^0.3.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'backpack-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'backpack-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'backpack-core/babel' {
  declare module.exports: any;
}

declare module 'backpack-core/config/paths' {
  declare module.exports: any;
}

declare module 'backpack-core/config/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'backpack-core/babel.js' {
  declare module.exports: $Exports<'backpack-core/babel'>;
}
declare module 'backpack-core/config/paths.js' {
  declare module.exports: $Exports<'backpack-core/config/paths'>;
}
declare module 'backpack-core/config/webpack.config.js' {
  declare module.exports: $Exports<'backpack-core/config/webpack.config'>;
}
