// flow-typed signature: 12ff6a69c705014206ff0fad9ee15f59
// flow-typed version: <<STUB>>/express-jwt-blacklist_v^1.1.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-jwt-blacklist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-jwt-blacklist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-jwt-blacklist/lib/debug' {
  declare module.exports: any;
}

declare module 'express-jwt-blacklist/lib/index' {
  declare module.exports: any;
}

declare module 'express-jwt-blacklist/lib/store/index' {
  declare module.exports: any;
}

declare module 'express-jwt-blacklist/lib/store/memcached' {
  declare module.exports: any;
}

declare module 'express-jwt-blacklist/lib/store/memory' {
  declare module.exports: any;
}

declare module 'express-jwt-blacklist/lib/store/redis' {
  declare module.exports: any;
}

declare module 'express-jwt-blacklist/lib/utils' {
  declare module.exports: any;
}

declare module 'express-jwt-blacklist/test/integration/memcached.spec' {
  declare module.exports: any;
}

declare module 'express-jwt-blacklist/test/integration/redis.spec' {
  declare module.exports: any;
}

declare module 'express-jwt-blacklist/test/lib.spec' {
  declare module.exports: any;
}

declare module 'express-jwt-blacklist/test/store.spec' {
  declare module.exports: any;
}

declare module 'express-jwt-blacklist/test/utils.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-jwt-blacklist/lib/debug.js' {
  declare module.exports: $Exports<'express-jwt-blacklist/lib/debug'>;
}
declare module 'express-jwt-blacklist/lib/index.js' {
  declare module.exports: $Exports<'express-jwt-blacklist/lib/index'>;
}
declare module 'express-jwt-blacklist/lib/store/index.js' {
  declare module.exports: $Exports<'express-jwt-blacklist/lib/store/index'>;
}
declare module 'express-jwt-blacklist/lib/store/memcached.js' {
  declare module.exports: $Exports<'express-jwt-blacklist/lib/store/memcached'>;
}
declare module 'express-jwt-blacklist/lib/store/memory.js' {
  declare module.exports: $Exports<'express-jwt-blacklist/lib/store/memory'>;
}
declare module 'express-jwt-blacklist/lib/store/redis.js' {
  declare module.exports: $Exports<'express-jwt-blacklist/lib/store/redis'>;
}
declare module 'express-jwt-blacklist/lib/utils.js' {
  declare module.exports: $Exports<'express-jwt-blacklist/lib/utils'>;
}
declare module 'express-jwt-blacklist/test/integration/memcached.spec.js' {
  declare module.exports: $Exports<'express-jwt-blacklist/test/integration/memcached.spec'>;
}
declare module 'express-jwt-blacklist/test/integration/redis.spec.js' {
  declare module.exports: $Exports<'express-jwt-blacklist/test/integration/redis.spec'>;
}
declare module 'express-jwt-blacklist/test/lib.spec.js' {
  declare module.exports: $Exports<'express-jwt-blacklist/test/lib.spec'>;
}
declare module 'express-jwt-blacklist/test/store.spec.js' {
  declare module.exports: $Exports<'express-jwt-blacklist/test/store.spec'>;
}
declare module 'express-jwt-blacklist/test/utils.spec.js' {
  declare module.exports: $Exports<'express-jwt-blacklist/test/utils.spec'>;
}
