// flow-typed signature: 7127f16e284300cf2c745747055e6d58
// flow-typed version: <<STUB>>/express-list-endpoints_v^3.0.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-list-endpoints'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-list-endpoints' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'express-list-endpoints/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'express-list-endpoints/src/index.js' {
  declare module.exports: $Exports<'express-list-endpoints/src/index'>;
}
