// flow-typed signature: a2590a8b2f3cad3bc3e6ad0c1530a6ea
// flow-typed version: <<STUB>>/nuxt_v^1.0.0-alpha.5/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nuxt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nuxt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nuxt/dist/app/client' {
  declare module.exports: any;
}

declare module 'nuxt/dist/app/components/nuxt-child' {
  declare module.exports: any;
}

declare module 'nuxt/dist/app/components/nuxt-link' {
  declare module.exports: any;
}

declare module 'nuxt/dist/app/index' {
  declare module.exports: any;
}

declare module 'nuxt/dist/app/middleware' {
  declare module.exports: any;
}

declare module 'nuxt/dist/app/router' {
  declare module.exports: any;
}

declare module 'nuxt/dist/app/server' {
  declare module.exports: any;
}

declare module 'nuxt/dist/app/store' {
  declare module.exports: any;
}

declare module 'nuxt/dist/app/utils' {
  declare module.exports: any;
}

declare module 'nuxt/dist/builder' {
  declare module.exports: any;
}

declare module 'nuxt/dist/core' {
  declare module.exports: any;
}

declare module 'nuxt/dist/nuxt' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nuxt/dist/app/client.js' {
  declare module.exports: $Exports<'nuxt/dist/app/client'>;
}
declare module 'nuxt/dist/app/components/nuxt-child.js' {
  declare module.exports: $Exports<'nuxt/dist/app/components/nuxt-child'>;
}
declare module 'nuxt/dist/app/components/nuxt-link.js' {
  declare module.exports: $Exports<'nuxt/dist/app/components/nuxt-link'>;
}
declare module 'nuxt/dist/app/index.js' {
  declare module.exports: $Exports<'nuxt/dist/app/index'>;
}
declare module 'nuxt/dist/app/middleware.js' {
  declare module.exports: $Exports<'nuxt/dist/app/middleware'>;
}
declare module 'nuxt/dist/app/router.js' {
  declare module.exports: $Exports<'nuxt/dist/app/router'>;
}
declare module 'nuxt/dist/app/server.js' {
  declare module.exports: $Exports<'nuxt/dist/app/server'>;
}
declare module 'nuxt/dist/app/store.js' {
  declare module.exports: $Exports<'nuxt/dist/app/store'>;
}
declare module 'nuxt/dist/app/utils.js' {
  declare module.exports: $Exports<'nuxt/dist/app/utils'>;
}
declare module 'nuxt/dist/builder.js' {
  declare module.exports: $Exports<'nuxt/dist/builder'>;
}
declare module 'nuxt/dist/core.js' {
  declare module.exports: $Exports<'nuxt/dist/core'>;
}
declare module 'nuxt/dist/nuxt.js' {
  declare module.exports: $Exports<'nuxt/dist/nuxt'>;
}
declare module 'nuxt/index' {
  declare module.exports: $Exports<'nuxt'>;
}
declare module 'nuxt/index.js' {
  declare module.exports: $Exports<'nuxt'>;
}
