// flow-typed signature: 77499e1f879556e58b6045c45c224b8b
// flow-typed version: <<STUB>>/oauth-libre_v^0.9.15/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'oauth-libre'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'oauth-libre' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'oauth-libre/examples/github-example' {
  declare module.exports: any;
}

declare module 'oauth-libre/examples/github-oauth2' {
  declare module.exports: any;
}

declare module 'oauth-libre/examples/promise-twitter-example' {
  declare module.exports: any;
}

declare module 'oauth-libre/examples/term.ie.oauth-HMAC-SHA1' {
  declare module.exports: any;
}

declare module 'oauth-libre/examples/twitter-example' {
  declare module.exports: any;
}

declare module 'oauth-libre/examples/twitter-oauth-promises' {
  declare module.exports: any;
}

declare module 'oauth-libre/lib/_utils' {
  declare module.exports: any;
}

declare module 'oauth-libre/lib/oauth-promise' {
  declare module.exports: any;
}

declare module 'oauth-libre/lib/oauth' {
  declare module.exports: any;
}

declare module 'oauth-libre/lib/oauth2-promise' {
  declare module.exports: any;
}

declare module 'oauth-libre/lib/oauth2' {
  declare module.exports: any;
}

declare module 'oauth-libre/lib/sha1' {
  declare module.exports: any;
}

declare module 'oauth-libre/tests/oauth2promise-tests' {
  declare module.exports: any;
}

declare module 'oauth-libre/tests/oauth2tests' {
  declare module.exports: any;
}

declare module 'oauth-libre/tests/oauthpromise-tests' {
  declare module.exports: any;
}

declare module 'oauth-libre/tests/oauthtests' {
  declare module.exports: any;
}

declare module 'oauth-libre/tests/sha1tests' {
  declare module.exports: any;
}

declare module 'oauth-libre/tests/shared' {
  declare module.exports: any;
}

// Filename aliases
declare module 'oauth-libre/examples/github-example.js' {
  declare module.exports: $Exports<'oauth-libre/examples/github-example'>;
}
declare module 'oauth-libre/examples/github-oauth2.js' {
  declare module.exports: $Exports<'oauth-libre/examples/github-oauth2'>;
}
declare module 'oauth-libre/examples/promise-twitter-example.js' {
  declare module.exports: $Exports<'oauth-libre/examples/promise-twitter-example'>;
}
declare module 'oauth-libre/examples/term.ie.oauth-HMAC-SHA1.js' {
  declare module.exports: $Exports<'oauth-libre/examples/term.ie.oauth-HMAC-SHA1'>;
}
declare module 'oauth-libre/examples/twitter-example.js' {
  declare module.exports: $Exports<'oauth-libre/examples/twitter-example'>;
}
declare module 'oauth-libre/examples/twitter-oauth-promises.js' {
  declare module.exports: $Exports<'oauth-libre/examples/twitter-oauth-promises'>;
}
declare module 'oauth-libre/index' {
  declare module.exports: $Exports<'oauth-libre'>;
}
declare module 'oauth-libre/index.js' {
  declare module.exports: $Exports<'oauth-libre'>;
}
declare module 'oauth-libre/lib/_utils.js' {
  declare module.exports: $Exports<'oauth-libre/lib/_utils'>;
}
declare module 'oauth-libre/lib/oauth-promise.js' {
  declare module.exports: $Exports<'oauth-libre/lib/oauth-promise'>;
}
declare module 'oauth-libre/lib/oauth.js' {
  declare module.exports: $Exports<'oauth-libre/lib/oauth'>;
}
declare module 'oauth-libre/lib/oauth2-promise.js' {
  declare module.exports: $Exports<'oauth-libre/lib/oauth2-promise'>;
}
declare module 'oauth-libre/lib/oauth2.js' {
  declare module.exports: $Exports<'oauth-libre/lib/oauth2'>;
}
declare module 'oauth-libre/lib/sha1.js' {
  declare module.exports: $Exports<'oauth-libre/lib/sha1'>;
}
declare module 'oauth-libre/tests/oauth2promise-tests.js' {
  declare module.exports: $Exports<'oauth-libre/tests/oauth2promise-tests'>;
}
declare module 'oauth-libre/tests/oauth2tests.js' {
  declare module.exports: $Exports<'oauth-libre/tests/oauth2tests'>;
}
declare module 'oauth-libre/tests/oauthpromise-tests.js' {
  declare module.exports: $Exports<'oauth-libre/tests/oauthpromise-tests'>;
}
declare module 'oauth-libre/tests/oauthtests.js' {
  declare module.exports: $Exports<'oauth-libre/tests/oauthtests'>;
}
declare module 'oauth-libre/tests/sha1tests.js' {
  declare module.exports: $Exports<'oauth-libre/tests/sha1tests'>;
}
declare module 'oauth-libre/tests/shared.js' {
  declare module.exports: $Exports<'oauth-libre/tests/shared'>;
}
