// flow-typed signature: 44abd2f12952bc1f92d9857ac2613bd7
// flow-typed version: <<STUB>>/socketio-jwt_v^4.5.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'socketio-jwt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'socketio-jwt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'socketio-jwt/example/socketsio-auth0-sample/index' {
  declare module.exports: any;
}

declare module 'socketio-jwt/lib/index' {
  declare module.exports: any;
}

declare module 'socketio-jwt/lib/UnauthorizedError' {
  declare module.exports: any;
}

declare module 'socketio-jwt/test/authorizer_namespaces.test' {
  declare module.exports: any;
}

declare module 'socketio-jwt/test/authorizer_noqs.test' {
  declare module.exports: any;
}

declare module 'socketio-jwt/test/authorizer_secret_function_noqs.test' {
  declare module.exports: any;
}

declare module 'socketio-jwt/test/authorizer_secret_function_qs.test' {
  declare module.exports: any;
}

declare module 'socketio-jwt/test/authorizer.test' {
  declare module.exports: any;
}

declare module 'socketio-jwt/test/fixture/index' {
  declare module.exports: any;
}

declare module 'socketio-jwt/test/fixture/namespace' {
  declare module.exports: any;
}

declare module 'socketio-jwt/test/fixture/secret_function' {
  declare module.exports: any;
}

// Filename aliases
declare module 'socketio-jwt/example/socketsio-auth0-sample/index.js' {
  declare module.exports: $Exports<'socketio-jwt/example/socketsio-auth0-sample/index'>;
}
declare module 'socketio-jwt/lib/index.js' {
  declare module.exports: $Exports<'socketio-jwt/lib/index'>;
}
declare module 'socketio-jwt/lib/UnauthorizedError.js' {
  declare module.exports: $Exports<'socketio-jwt/lib/UnauthorizedError'>;
}
declare module 'socketio-jwt/test/authorizer_namespaces.test.js' {
  declare module.exports: $Exports<'socketio-jwt/test/authorizer_namespaces.test'>;
}
declare module 'socketio-jwt/test/authorizer_noqs.test.js' {
  declare module.exports: $Exports<'socketio-jwt/test/authorizer_noqs.test'>;
}
declare module 'socketio-jwt/test/authorizer_secret_function_noqs.test.js' {
  declare module.exports: $Exports<'socketio-jwt/test/authorizer_secret_function_noqs.test'>;
}
declare module 'socketio-jwt/test/authorizer_secret_function_qs.test.js' {
  declare module.exports: $Exports<'socketio-jwt/test/authorizer_secret_function_qs.test'>;
}
declare module 'socketio-jwt/test/authorizer.test.js' {
  declare module.exports: $Exports<'socketio-jwt/test/authorizer.test'>;
}
declare module 'socketio-jwt/test/fixture/index.js' {
  declare module.exports: $Exports<'socketio-jwt/test/fixture/index'>;
}
declare module 'socketio-jwt/test/fixture/namespace.js' {
  declare module.exports: $Exports<'socketio-jwt/test/fixture/namespace'>;
}
declare module 'socketio-jwt/test/fixture/secret_function.js' {
  declare module.exports: $Exports<'socketio-jwt/test/fixture/secret_function'>;
}
