// flow-typed signature: 22dc287c3c98464dd94c3ae11faff1cd
// flow-typed version: <<STUB>>/speakeasy_v^2.0.0/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'speakeasy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'speakeasy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'speakeasy/index' {
  declare module.exports: $Exports<'speakeasy'>;
}
declare module 'speakeasy/index.js' {
  declare module.exports: $Exports<'speakeasy'>;
}
