// flow-typed signature: f3557b215011c4f051a6e3b2710bfd51
// flow-typed version: <<STUB>>/video.js_v^5.20.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'video.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'video.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'video.js/dist/alt/video.novtt' {
  declare module.exports: any;
}

declare module 'video.js/dist/alt/video.novtt.min' {
  declare module.exports: any;
}

declare module 'video.js/dist/ie8/videojs-ie8' {
  declare module.exports: any;
}

declare module 'video.js/dist/ie8/videojs-ie8.min' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ar' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ba' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/bg' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ca' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/cs' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/da' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/de' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/el' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/en' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/es' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/fa' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/fi' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/fr' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/hr' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/hu' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/it' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ja' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ko' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/nb' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/nl' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/nn' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/pl' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/pt-BR' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/ru' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/sr' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/sv' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/tr' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/uk' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/vi' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/zh-CN' {
  declare module.exports: any;
}

declare module 'video.js/dist/lang/zh-TW' {
  declare module.exports: any;
}

declare module 'video.js/dist/video' {
  declare module.exports: any;
}

declare module 'video.js/dist/video.min' {
  declare module.exports: any;
}

declare module 'video.js/es5/big-play-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/button' {
  declare module.exports: any;
}

declare module 'video.js/es5/clickable-component' {
  declare module.exports: any;
}

declare module 'video.js/es5/close-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/component' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/audio-track-controls/audio-track-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/audio-track-controls/audio-track-menu-item' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/control-bar' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/fullscreen-toggle' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/live-display' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/mute-toggle' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/play-toggle' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/playback-rate-menu/playback-rate-menu-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/playback-rate-menu/playback-rate-menu-item' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/progress-control/load-progress-bar' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/progress-control/mouse-time-display' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/progress-control/play-progress-bar' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/progress-control/progress-control' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/progress-control/seek-bar' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/progress-control/tooltip-progress-bar' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/spacer-controls/custom-control-spacer' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/spacer-controls/spacer' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/text-track-controls/caption-settings-menu-item' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/text-track-controls/captions-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/text-track-controls/chapters-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/text-track-controls/chapters-track-menu-item' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/text-track-controls/descriptions-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/text-track-controls/off-text-track-menu-item' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/text-track-controls/subtitles-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/text-track-controls/text-track-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/text-track-controls/text-track-menu-item' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/time-controls/current-time-display' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/time-controls/duration-display' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/time-controls/remaining-time-display' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/time-controls/time-divider' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/track-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/volume-control/volume-bar' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/volume-control/volume-control' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/volume-control/volume-level' {
  declare module.exports: any;
}

declare module 'video.js/es5/control-bar/volume-menu-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/error-display' {
  declare module.exports: any;
}

declare module 'video.js/es5/event-target' {
  declare module.exports: any;
}

declare module 'video.js/es5/extend' {
  declare module.exports: any;
}

declare module 'video.js/es5/fullscreen-api' {
  declare module.exports: any;
}

declare module 'video.js/es5/loading-spinner' {
  declare module.exports: any;
}

declare module 'video.js/es5/media-error' {
  declare module.exports: any;
}

declare module 'video.js/es5/menu/menu-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/menu/menu-item' {
  declare module.exports: any;
}

declare module 'video.js/es5/menu/menu' {
  declare module.exports: any;
}

declare module 'video.js/es5/modal-dialog' {
  declare module.exports: any;
}

declare module 'video.js/es5/player' {
  declare module.exports: any;
}

declare module 'video.js/es5/plugins' {
  declare module.exports: any;
}

declare module 'video.js/es5/popup/popup-button' {
  declare module.exports: any;
}

declare module 'video.js/es5/popup/popup' {
  declare module.exports: any;
}

declare module 'video.js/es5/poster-image' {
  declare module.exports: any;
}

declare module 'video.js/es5/setup' {
  declare module.exports: any;
}

declare module 'video.js/es5/slider/slider' {
  declare module.exports: any;
}

declare module 'video.js/es5/tech/flash-rtmp' {
  declare module.exports: any;
}

declare module 'video.js/es5/tech/flash' {
  declare module.exports: any;
}

declare module 'video.js/es5/tech/html5' {
  declare module.exports: any;
}

declare module 'video.js/es5/tech/loader' {
  declare module.exports: any;
}

declare module 'video.js/es5/tech/tech' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/audio-track-list' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/audio-track' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/html-track-element-list' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/html-track-element' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/text-track-cue-list' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/text-track-display' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/text-track-list-converter' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/text-track-list' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/text-track-settings' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/text-track' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/track-enums' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/track-list' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/track' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/video-track-list' {
  declare module.exports: any;
}

declare module 'video.js/es5/tracks/video-track' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/browser' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/buffer' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/computed-style' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/dom' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/events' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/fn' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/format-time' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/guid' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/log' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/merge-options' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/obj' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/stylesheet' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/time-ranges' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/to-title-case' {
  declare module.exports: any;
}

declare module 'video.js/es5/utils/url' {
  declare module.exports: any;
}

declare module 'video.js/es5/video' {
  declare module.exports: any;
}

// Filename aliases
declare module 'video.js/dist/alt/video.novtt.js' {
  declare module.exports: $Exports<'video.js/dist/alt/video.novtt'>;
}
declare module 'video.js/dist/alt/video.novtt.min.js' {
  declare module.exports: $Exports<'video.js/dist/alt/video.novtt.min'>;
}
declare module 'video.js/dist/ie8/videojs-ie8.js' {
  declare module.exports: $Exports<'video.js/dist/ie8/videojs-ie8'>;
}
declare module 'video.js/dist/ie8/videojs-ie8.min.js' {
  declare module.exports: $Exports<'video.js/dist/ie8/videojs-ie8.min'>;
}
declare module 'video.js/dist/lang/ar.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ar'>;
}
declare module 'video.js/dist/lang/ba.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ba'>;
}
declare module 'video.js/dist/lang/bg.js' {
  declare module.exports: $Exports<'video.js/dist/lang/bg'>;
}
declare module 'video.js/dist/lang/ca.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ca'>;
}
declare module 'video.js/dist/lang/cs.js' {
  declare module.exports: $Exports<'video.js/dist/lang/cs'>;
}
declare module 'video.js/dist/lang/da.js' {
  declare module.exports: $Exports<'video.js/dist/lang/da'>;
}
declare module 'video.js/dist/lang/de.js' {
  declare module.exports: $Exports<'video.js/dist/lang/de'>;
}
declare module 'video.js/dist/lang/el.js' {
  declare module.exports: $Exports<'video.js/dist/lang/el'>;
}
declare module 'video.js/dist/lang/en.js' {
  declare module.exports: $Exports<'video.js/dist/lang/en'>;
}
declare module 'video.js/dist/lang/es.js' {
  declare module.exports: $Exports<'video.js/dist/lang/es'>;
}
declare module 'video.js/dist/lang/fa.js' {
  declare module.exports: $Exports<'video.js/dist/lang/fa'>;
}
declare module 'video.js/dist/lang/fi.js' {
  declare module.exports: $Exports<'video.js/dist/lang/fi'>;
}
declare module 'video.js/dist/lang/fr.js' {
  declare module.exports: $Exports<'video.js/dist/lang/fr'>;
}
declare module 'video.js/dist/lang/hr.js' {
  declare module.exports: $Exports<'video.js/dist/lang/hr'>;
}
declare module 'video.js/dist/lang/hu.js' {
  declare module.exports: $Exports<'video.js/dist/lang/hu'>;
}
declare module 'video.js/dist/lang/it.js' {
  declare module.exports: $Exports<'video.js/dist/lang/it'>;
}
declare module 'video.js/dist/lang/ja.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ja'>;
}
declare module 'video.js/dist/lang/ko.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ko'>;
}
declare module 'video.js/dist/lang/nb.js' {
  declare module.exports: $Exports<'video.js/dist/lang/nb'>;
}
declare module 'video.js/dist/lang/nl.js' {
  declare module.exports: $Exports<'video.js/dist/lang/nl'>;
}
declare module 'video.js/dist/lang/nn.js' {
  declare module.exports: $Exports<'video.js/dist/lang/nn'>;
}
declare module 'video.js/dist/lang/pl.js' {
  declare module.exports: $Exports<'video.js/dist/lang/pl'>;
}
declare module 'video.js/dist/lang/pt-BR.js' {
  declare module.exports: $Exports<'video.js/dist/lang/pt-BR'>;
}
declare module 'video.js/dist/lang/ru.js' {
  declare module.exports: $Exports<'video.js/dist/lang/ru'>;
}
declare module 'video.js/dist/lang/sr.js' {
  declare module.exports: $Exports<'video.js/dist/lang/sr'>;
}
declare module 'video.js/dist/lang/sv.js' {
  declare module.exports: $Exports<'video.js/dist/lang/sv'>;
}
declare module 'video.js/dist/lang/tr.js' {
  declare module.exports: $Exports<'video.js/dist/lang/tr'>;
}
declare module 'video.js/dist/lang/uk.js' {
  declare module.exports: $Exports<'video.js/dist/lang/uk'>;
}
declare module 'video.js/dist/lang/vi.js' {
  declare module.exports: $Exports<'video.js/dist/lang/vi'>;
}
declare module 'video.js/dist/lang/zh-CN.js' {
  declare module.exports: $Exports<'video.js/dist/lang/zh-CN'>;
}
declare module 'video.js/dist/lang/zh-TW.js' {
  declare module.exports: $Exports<'video.js/dist/lang/zh-TW'>;
}
declare module 'video.js/dist/video.js' {
  declare module.exports: $Exports<'video.js/dist/video'>;
}
declare module 'video.js/dist/video.min.js' {
  declare module.exports: $Exports<'video.js/dist/video.min'>;
}
declare module 'video.js/es5/big-play-button.js' {
  declare module.exports: $Exports<'video.js/es5/big-play-button'>;
}
declare module 'video.js/es5/button.js' {
  declare module.exports: $Exports<'video.js/es5/button'>;
}
declare module 'video.js/es5/clickable-component.js' {
  declare module.exports: $Exports<'video.js/es5/clickable-component'>;
}
declare module 'video.js/es5/close-button.js' {
  declare module.exports: $Exports<'video.js/es5/close-button'>;
}
declare module 'video.js/es5/component.js' {
  declare module.exports: $Exports<'video.js/es5/component'>;
}
declare module 'video.js/es5/control-bar/audio-track-controls/audio-track-button.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/audio-track-controls/audio-track-button'>;
}
declare module 'video.js/es5/control-bar/audio-track-controls/audio-track-menu-item.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/audio-track-controls/audio-track-menu-item'>;
}
declare module 'video.js/es5/control-bar/control-bar.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/control-bar'>;
}
declare module 'video.js/es5/control-bar/fullscreen-toggle.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/fullscreen-toggle'>;
}
declare module 'video.js/es5/control-bar/live-display.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/live-display'>;
}
declare module 'video.js/es5/control-bar/mute-toggle.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/mute-toggle'>;
}
declare module 'video.js/es5/control-bar/play-toggle.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/play-toggle'>;
}
declare module 'video.js/es5/control-bar/playback-rate-menu/playback-rate-menu-button.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/playback-rate-menu/playback-rate-menu-button'>;
}
declare module 'video.js/es5/control-bar/playback-rate-menu/playback-rate-menu-item.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/playback-rate-menu/playback-rate-menu-item'>;
}
declare module 'video.js/es5/control-bar/progress-control/load-progress-bar.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/progress-control/load-progress-bar'>;
}
declare module 'video.js/es5/control-bar/progress-control/mouse-time-display.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/progress-control/mouse-time-display'>;
}
declare module 'video.js/es5/control-bar/progress-control/play-progress-bar.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/progress-control/play-progress-bar'>;
}
declare module 'video.js/es5/control-bar/progress-control/progress-control.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/progress-control/progress-control'>;
}
declare module 'video.js/es5/control-bar/progress-control/seek-bar.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/progress-control/seek-bar'>;
}
declare module 'video.js/es5/control-bar/progress-control/tooltip-progress-bar.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/progress-control/tooltip-progress-bar'>;
}
declare module 'video.js/es5/control-bar/spacer-controls/custom-control-spacer.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/spacer-controls/custom-control-spacer'>;
}
declare module 'video.js/es5/control-bar/spacer-controls/spacer.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/spacer-controls/spacer'>;
}
declare module 'video.js/es5/control-bar/text-track-controls/caption-settings-menu-item.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/text-track-controls/caption-settings-menu-item'>;
}
declare module 'video.js/es5/control-bar/text-track-controls/captions-button.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/text-track-controls/captions-button'>;
}
declare module 'video.js/es5/control-bar/text-track-controls/chapters-button.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/text-track-controls/chapters-button'>;
}
declare module 'video.js/es5/control-bar/text-track-controls/chapters-track-menu-item.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/text-track-controls/chapters-track-menu-item'>;
}
declare module 'video.js/es5/control-bar/text-track-controls/descriptions-button.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/text-track-controls/descriptions-button'>;
}
declare module 'video.js/es5/control-bar/text-track-controls/off-text-track-menu-item.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/text-track-controls/off-text-track-menu-item'>;
}
declare module 'video.js/es5/control-bar/text-track-controls/subtitles-button.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/text-track-controls/subtitles-button'>;
}
declare module 'video.js/es5/control-bar/text-track-controls/text-track-button.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/text-track-controls/text-track-button'>;
}
declare module 'video.js/es5/control-bar/text-track-controls/text-track-menu-item.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/text-track-controls/text-track-menu-item'>;
}
declare module 'video.js/es5/control-bar/time-controls/current-time-display.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/time-controls/current-time-display'>;
}
declare module 'video.js/es5/control-bar/time-controls/duration-display.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/time-controls/duration-display'>;
}
declare module 'video.js/es5/control-bar/time-controls/remaining-time-display.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/time-controls/remaining-time-display'>;
}
declare module 'video.js/es5/control-bar/time-controls/time-divider.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/time-controls/time-divider'>;
}
declare module 'video.js/es5/control-bar/track-button.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/track-button'>;
}
declare module 'video.js/es5/control-bar/volume-control/volume-bar.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/volume-control/volume-bar'>;
}
declare module 'video.js/es5/control-bar/volume-control/volume-control.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/volume-control/volume-control'>;
}
declare module 'video.js/es5/control-bar/volume-control/volume-level.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/volume-control/volume-level'>;
}
declare module 'video.js/es5/control-bar/volume-menu-button.js' {
  declare module.exports: $Exports<'video.js/es5/control-bar/volume-menu-button'>;
}
declare module 'video.js/es5/error-display.js' {
  declare module.exports: $Exports<'video.js/es5/error-display'>;
}
declare module 'video.js/es5/event-target.js' {
  declare module.exports: $Exports<'video.js/es5/event-target'>;
}
declare module 'video.js/es5/extend.js' {
  declare module.exports: $Exports<'video.js/es5/extend'>;
}
declare module 'video.js/es5/fullscreen-api.js' {
  declare module.exports: $Exports<'video.js/es5/fullscreen-api'>;
}
declare module 'video.js/es5/loading-spinner.js' {
  declare module.exports: $Exports<'video.js/es5/loading-spinner'>;
}
declare module 'video.js/es5/media-error.js' {
  declare module.exports: $Exports<'video.js/es5/media-error'>;
}
declare module 'video.js/es5/menu/menu-button.js' {
  declare module.exports: $Exports<'video.js/es5/menu/menu-button'>;
}
declare module 'video.js/es5/menu/menu-item.js' {
  declare module.exports: $Exports<'video.js/es5/menu/menu-item'>;
}
declare module 'video.js/es5/menu/menu.js' {
  declare module.exports: $Exports<'video.js/es5/menu/menu'>;
}
declare module 'video.js/es5/modal-dialog.js' {
  declare module.exports: $Exports<'video.js/es5/modal-dialog'>;
}
declare module 'video.js/es5/player.js' {
  declare module.exports: $Exports<'video.js/es5/player'>;
}
declare module 'video.js/es5/plugins.js' {
  declare module.exports: $Exports<'video.js/es5/plugins'>;
}
declare module 'video.js/es5/popup/popup-button.js' {
  declare module.exports: $Exports<'video.js/es5/popup/popup-button'>;
}
declare module 'video.js/es5/popup/popup.js' {
  declare module.exports: $Exports<'video.js/es5/popup/popup'>;
}
declare module 'video.js/es5/poster-image.js' {
  declare module.exports: $Exports<'video.js/es5/poster-image'>;
}
declare module 'video.js/es5/setup.js' {
  declare module.exports: $Exports<'video.js/es5/setup'>;
}
declare module 'video.js/es5/slider/slider.js' {
  declare module.exports: $Exports<'video.js/es5/slider/slider'>;
}
declare module 'video.js/es5/tech/flash-rtmp.js' {
  declare module.exports: $Exports<'video.js/es5/tech/flash-rtmp'>;
}
declare module 'video.js/es5/tech/flash.js' {
  declare module.exports: $Exports<'video.js/es5/tech/flash'>;
}
declare module 'video.js/es5/tech/html5.js' {
  declare module.exports: $Exports<'video.js/es5/tech/html5'>;
}
declare module 'video.js/es5/tech/loader.js' {
  declare module.exports: $Exports<'video.js/es5/tech/loader'>;
}
declare module 'video.js/es5/tech/tech.js' {
  declare module.exports: $Exports<'video.js/es5/tech/tech'>;
}
declare module 'video.js/es5/tracks/audio-track-list.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/audio-track-list'>;
}
declare module 'video.js/es5/tracks/audio-track.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/audio-track'>;
}
declare module 'video.js/es5/tracks/html-track-element-list.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/html-track-element-list'>;
}
declare module 'video.js/es5/tracks/html-track-element.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/html-track-element'>;
}
declare module 'video.js/es5/tracks/text-track-cue-list.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/text-track-cue-list'>;
}
declare module 'video.js/es5/tracks/text-track-display.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/text-track-display'>;
}
declare module 'video.js/es5/tracks/text-track-list-converter.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/text-track-list-converter'>;
}
declare module 'video.js/es5/tracks/text-track-list.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/text-track-list'>;
}
declare module 'video.js/es5/tracks/text-track-settings.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/text-track-settings'>;
}
declare module 'video.js/es5/tracks/text-track.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/text-track'>;
}
declare module 'video.js/es5/tracks/track-enums.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/track-enums'>;
}
declare module 'video.js/es5/tracks/track-list.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/track-list'>;
}
declare module 'video.js/es5/tracks/track.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/track'>;
}
declare module 'video.js/es5/tracks/video-track-list.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/video-track-list'>;
}
declare module 'video.js/es5/tracks/video-track.js' {
  declare module.exports: $Exports<'video.js/es5/tracks/video-track'>;
}
declare module 'video.js/es5/utils/browser.js' {
  declare module.exports: $Exports<'video.js/es5/utils/browser'>;
}
declare module 'video.js/es5/utils/buffer.js' {
  declare module.exports: $Exports<'video.js/es5/utils/buffer'>;
}
declare module 'video.js/es5/utils/computed-style.js' {
  declare module.exports: $Exports<'video.js/es5/utils/computed-style'>;
}
declare module 'video.js/es5/utils/dom.js' {
  declare module.exports: $Exports<'video.js/es5/utils/dom'>;
}
declare module 'video.js/es5/utils/events.js' {
  declare module.exports: $Exports<'video.js/es5/utils/events'>;
}
declare module 'video.js/es5/utils/fn.js' {
  declare module.exports: $Exports<'video.js/es5/utils/fn'>;
}
declare module 'video.js/es5/utils/format-time.js' {
  declare module.exports: $Exports<'video.js/es5/utils/format-time'>;
}
declare module 'video.js/es5/utils/guid.js' {
  declare module.exports: $Exports<'video.js/es5/utils/guid'>;
}
declare module 'video.js/es5/utils/log.js' {
  declare module.exports: $Exports<'video.js/es5/utils/log'>;
}
declare module 'video.js/es5/utils/merge-options.js' {
  declare module.exports: $Exports<'video.js/es5/utils/merge-options'>;
}
declare module 'video.js/es5/utils/obj.js' {
  declare module.exports: $Exports<'video.js/es5/utils/obj'>;
}
declare module 'video.js/es5/utils/stylesheet.js' {
  declare module.exports: $Exports<'video.js/es5/utils/stylesheet'>;
}
declare module 'video.js/es5/utils/time-ranges.js' {
  declare module.exports: $Exports<'video.js/es5/utils/time-ranges'>;
}
declare module 'video.js/es5/utils/to-title-case.js' {
  declare module.exports: $Exports<'video.js/es5/utils/to-title-case'>;
}
declare module 'video.js/es5/utils/url.js' {
  declare module.exports: $Exports<'video.js/es5/utils/url'>;
}
declare module 'video.js/es5/video.js' {
  declare module.exports: $Exports<'video.js/es5/video'>;
}
