// flow-typed signature: b7c845da46d3124fa5901a1025b01eae
// flow-typed version: <<STUB>>/videojs-hotkeys_vgit+https://github.com/Pedrock/videojs-hotkeys.git/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'videojs-hotkeys'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'videojs-hotkeys' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'videojs-hotkeys/Gruntfile' {
  declare module.exports: any;
}

declare module 'videojs-hotkeys/videojs.hotkeys' {
  declare module.exports: any;
}

declare module 'videojs-hotkeys/videojs.hotkeys.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'videojs-hotkeys/Gruntfile.js' {
  declare module.exports: $Exports<'videojs-hotkeys/Gruntfile'>;
}
declare module 'videojs-hotkeys/videojs.hotkeys.js' {
  declare module.exports: $Exports<'videojs-hotkeys/videojs.hotkeys'>;
}
declare module 'videojs-hotkeys/videojs.hotkeys.min.js' {
  declare module.exports: $Exports<'videojs-hotkeys/videojs.hotkeys.min'>;
}
