// flow-typed signature: cfdb89d4d6516a34c1dd29383a0f8c0f
// flow-typed version: <<STUB>>/vue-server-renderer_v^2.4.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue-server-renderer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue-server-renderer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue-server-renderer/basic' {
  declare module.exports: any;
}

declare module 'vue-server-renderer/build' {
  declare module.exports: any;
}

declare module 'vue-server-renderer/client-plugin' {
  declare module.exports: any;
}

declare module 'vue-server-renderer/server-plugin' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue-server-renderer/basic.js' {
  declare module.exports: $Exports<'vue-server-renderer/basic'>;
}
declare module 'vue-server-renderer/build.js' {
  declare module.exports: $Exports<'vue-server-renderer/build'>;
}
declare module 'vue-server-renderer/client-plugin.js' {
  declare module.exports: $Exports<'vue-server-renderer/client-plugin'>;
}
declare module 'vue-server-renderer/index' {
  declare module.exports: $Exports<'vue-server-renderer'>;
}
declare module 'vue-server-renderer/index.js' {
  declare module.exports: $Exports<'vue-server-renderer'>;
}
declare module 'vue-server-renderer/server-plugin.js' {
  declare module.exports: $Exports<'vue-server-renderer/server-plugin'>;
}
