// flow-typed signature: 80c6cf9b22b87e1e31658f77c3a44a2b
// flow-typed version: <<STUB>>/vue_v^2.4.1/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vue'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vue' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vue/dist/vue.common' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.esm' {
  declare module.exports: any;
}

declare module 'vue/dist/vue' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.min' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.runtime.common' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.runtime.esm' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.runtime' {
  declare module.exports: any;
}

declare module 'vue/dist/vue.runtime.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vue/dist/vue.common.js' {
  declare module.exports: $Exports<'vue/dist/vue.common'>;
}
declare module 'vue/dist/vue.esm.js' {
  declare module.exports: $Exports<'vue/dist/vue.esm'>;
}
declare module 'vue/dist/vue.js' {
  declare module.exports: $Exports<'vue/dist/vue'>;
}
declare module 'vue/dist/vue.min.js' {
  declare module.exports: $Exports<'vue/dist/vue.min'>;
}
declare module 'vue/dist/vue.runtime.common.js' {
  declare module.exports: $Exports<'vue/dist/vue.runtime.common'>;
}
declare module 'vue/dist/vue.runtime.esm.js' {
  declare module.exports: $Exports<'vue/dist/vue.runtime.esm'>;
}
declare module 'vue/dist/vue.runtime.js' {
  declare module.exports: $Exports<'vue/dist/vue.runtime'>;
}
declare module 'vue/dist/vue.runtime.min.js' {
  declare module.exports: $Exports<'vue/dist/vue.runtime.min'>;
}
