// flow-typed signature: ecc8587cd97dea387c9d5995e407c6a1
// flow-typed version: <<STUB>>/vuetify_v^0.14.2/flow_v0.51.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vuetify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vuetify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vuetify/build/build' {
  declare module.exports: any;
}

declare module 'vuetify/build/config' {
  declare module.exports: any;
}

declare module 'vuetify/build/webpack.base.config' {
  declare module.exports: any;
}

declare module 'vuetify/dist/vuetify' {
  declare module.exports: any;
}

declare module 'vuetify/dist/vuetify.min' {
  declare module.exports: any;
}

declare module 'vuetify/postcss.config' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/_index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/alerts/Alert' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/alerts/Alert.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/alerts/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/app/App' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/app/App.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/app/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/avatars/Avatar.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/avatars/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/bottom-nav/BottomNav' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/bottom-nav/BottomNav.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/bottom-nav/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/breadcrumbs/Breadcrumbs' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/breadcrumbs/Breadcrumbs.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/breadcrumbs/BreadcrumbsItem' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/breadcrumbs/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/buttons/Button' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/buttons/Button.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/buttons/ButtonToggle.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/buttons/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/buttons/SpeedDial' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/cards/Card' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/cards/CardMedia' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/cards/CardRow' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/cards/CardTitle' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/cards/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/carousel/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/chips/Chip' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/chips/Chip.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/chips/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/dialogs/Dialog' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/dialogs/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/dividers/Divider' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/dividers/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/expansion-panel/ExpansionPanel' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/expansion-panel/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/footer/Footer' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/footer/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/grid/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/icons/Icon' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/icons/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/lists/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/lists/List' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/lists/ListGroup' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/lists/ListTile' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/lists/ListTile.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/lists/ListTileAction' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/menus/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/menus/Menu' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/menus/Menu.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/menus/mixins/activator' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/menus/mixins/generators' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/menus/mixins/keyable' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/menus/mixins/position' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/menus/mixins/utils' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/navigation-drawer/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/navigation-drawer/NavigationDrawer' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/pagination/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/pagination/Pagination.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/parallax/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/parallax/Parallax' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/pickers/DatePicker' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/pickers/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/pickers/mixins/date-header' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/pickers/mixins/date-table' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/pickers/mixins/date-title' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/pickers/mixins/date-years' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/pickers/mixins/time-body' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/pickers/mixins/time-title' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/pickers/TimePicker' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/pickers/TimePicker.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/progress/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/selection-controls/Checkbox' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/selection-controls/Checkbox.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/selection-controls/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/selection-controls/Radio' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/selection-controls/Switch' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/selects/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/selects/mixins/autocomplete' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/selects/mixins/generators' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/selects/Select' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/sliders/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/sliders/Slider' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/snackbars/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/snackbars/Snackbar' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/snackbars/Snackbar.spec' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/steppers/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/steppers/Stepper' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/steppers/StepperContent' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/steppers/StepperStep' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/subheaders/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/subheaders/Subheader' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/tables/DataTable' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/tables/EditDialog' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/tables/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/tables/mixins/body' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/tables/mixins/foot' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/tables/mixins/head' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/tables/mixins/progress' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/tabs/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/tabs/Tabs' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/tabs/TabsBar' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/tabs/TabsContent' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/tabs/TabsItem' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/text-fields/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/text-fields/TextField' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/toolbar/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/toolbar/SystemBar' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/toolbar/Toolbar' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/toolbar/ToolbarSideIcon' {
  declare module.exports: any;
}

declare module 'vuetify/src/components/transitions/_index' {
  declare module.exports: any;
}

declare module 'vuetify/src/directives/_index' {
  declare module.exports: any;
}

declare module 'vuetify/src/directives/badge' {
  declare module.exports: any;
}

declare module 'vuetify/src/directives/click-outside' {
  declare module.exports: any;
}

declare module 'vuetify/src/directives/ripple' {
  declare module.exports: any;
}

declare module 'vuetify/src/directives/tooltip' {
  declare module.exports: any;
}

declare module 'vuetify/src/index' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/bootable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/colorable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/contextualable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/detachable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/expand-transition' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/filterable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/input' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/overlayable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/picker' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/positionable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/resizable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/route-link' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/selectable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/swipeable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/themeable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/toggleable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/transitionable' {
  declare module.exports: any;
}

declare module 'vuetify/src/mixins/translatable' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/helpers' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/load' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/testing' {
  declare module.exports: any;
}

declare module 'vuetify/src/util/touch' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vuetify/build/build.js' {
  declare module.exports: $Exports<'vuetify/build/build'>;
}
declare module 'vuetify/build/config.js' {
  declare module.exports: $Exports<'vuetify/build/config'>;
}
declare module 'vuetify/build/webpack.base.config.js' {
  declare module.exports: $Exports<'vuetify/build/webpack.base.config'>;
}
declare module 'vuetify/dist/vuetify.js' {
  declare module.exports: $Exports<'vuetify/dist/vuetify'>;
}
declare module 'vuetify/dist/vuetify.min.js' {
  declare module.exports: $Exports<'vuetify/dist/vuetify.min'>;
}
declare module 'vuetify/postcss.config.js' {
  declare module.exports: $Exports<'vuetify/postcss.config'>;
}
declare module 'vuetify/src/components/_index.js' {
  declare module.exports: $Exports<'vuetify/src/components/_index'>;
}
declare module 'vuetify/src/components/alerts/Alert.js' {
  declare module.exports: $Exports<'vuetify/src/components/alerts/Alert'>;
}
declare module 'vuetify/src/components/alerts/Alert.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/alerts/Alert.spec'>;
}
declare module 'vuetify/src/components/alerts/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/alerts/index'>;
}
declare module 'vuetify/src/components/app/App.js' {
  declare module.exports: $Exports<'vuetify/src/components/app/App'>;
}
declare module 'vuetify/src/components/app/App.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/app/App.spec'>;
}
declare module 'vuetify/src/components/app/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/app/index'>;
}
declare module 'vuetify/src/components/avatars/Avatar.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/avatars/Avatar.spec'>;
}
declare module 'vuetify/src/components/avatars/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/avatars/index'>;
}
declare module 'vuetify/src/components/bottom-nav/BottomNav.js' {
  declare module.exports: $Exports<'vuetify/src/components/bottom-nav/BottomNav'>;
}
declare module 'vuetify/src/components/bottom-nav/BottomNav.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/bottom-nav/BottomNav.spec'>;
}
declare module 'vuetify/src/components/bottom-nav/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/bottom-nav/index'>;
}
declare module 'vuetify/src/components/breadcrumbs/Breadcrumbs.js' {
  declare module.exports: $Exports<'vuetify/src/components/breadcrumbs/Breadcrumbs'>;
}
declare module 'vuetify/src/components/breadcrumbs/Breadcrumbs.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/breadcrumbs/Breadcrumbs.spec'>;
}
declare module 'vuetify/src/components/breadcrumbs/BreadcrumbsItem.js' {
  declare module.exports: $Exports<'vuetify/src/components/breadcrumbs/BreadcrumbsItem'>;
}
declare module 'vuetify/src/components/breadcrumbs/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/breadcrumbs/index'>;
}
declare module 'vuetify/src/components/buttons/Button.js' {
  declare module.exports: $Exports<'vuetify/src/components/buttons/Button'>;
}
declare module 'vuetify/src/components/buttons/Button.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/buttons/Button.spec'>;
}
declare module 'vuetify/src/components/buttons/ButtonToggle.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/buttons/ButtonToggle.spec'>;
}
declare module 'vuetify/src/components/buttons/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/buttons/index'>;
}
declare module 'vuetify/src/components/buttons/SpeedDial.js' {
  declare module.exports: $Exports<'vuetify/src/components/buttons/SpeedDial'>;
}
declare module 'vuetify/src/components/cards/Card.js' {
  declare module.exports: $Exports<'vuetify/src/components/cards/Card'>;
}
declare module 'vuetify/src/components/cards/CardMedia.js' {
  declare module.exports: $Exports<'vuetify/src/components/cards/CardMedia'>;
}
declare module 'vuetify/src/components/cards/CardRow.js' {
  declare module.exports: $Exports<'vuetify/src/components/cards/CardRow'>;
}
declare module 'vuetify/src/components/cards/CardTitle.js' {
  declare module.exports: $Exports<'vuetify/src/components/cards/CardTitle'>;
}
declare module 'vuetify/src/components/cards/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/cards/index'>;
}
declare module 'vuetify/src/components/carousel/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/carousel/index'>;
}
declare module 'vuetify/src/components/chips/Chip.js' {
  declare module.exports: $Exports<'vuetify/src/components/chips/Chip'>;
}
declare module 'vuetify/src/components/chips/Chip.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/chips/Chip.spec'>;
}
declare module 'vuetify/src/components/chips/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/chips/index'>;
}
declare module 'vuetify/src/components/dialogs/Dialog.js' {
  declare module.exports: $Exports<'vuetify/src/components/dialogs/Dialog'>;
}
declare module 'vuetify/src/components/dialogs/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/dialogs/index'>;
}
declare module 'vuetify/src/components/dividers/Divider.js' {
  declare module.exports: $Exports<'vuetify/src/components/dividers/Divider'>;
}
declare module 'vuetify/src/components/dividers/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/dividers/index'>;
}
declare module 'vuetify/src/components/expansion-panel/ExpansionPanel.js' {
  declare module.exports: $Exports<'vuetify/src/components/expansion-panel/ExpansionPanel'>;
}
declare module 'vuetify/src/components/expansion-panel/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/expansion-panel/index'>;
}
declare module 'vuetify/src/components/footer/Footer.js' {
  declare module.exports: $Exports<'vuetify/src/components/footer/Footer'>;
}
declare module 'vuetify/src/components/footer/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/footer/index'>;
}
declare module 'vuetify/src/components/grid/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/grid/index'>;
}
declare module 'vuetify/src/components/icons/Icon.js' {
  declare module.exports: $Exports<'vuetify/src/components/icons/Icon'>;
}
declare module 'vuetify/src/components/icons/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/icons/index'>;
}
declare module 'vuetify/src/components/lists/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/lists/index'>;
}
declare module 'vuetify/src/components/lists/List.js' {
  declare module.exports: $Exports<'vuetify/src/components/lists/List'>;
}
declare module 'vuetify/src/components/lists/ListGroup.js' {
  declare module.exports: $Exports<'vuetify/src/components/lists/ListGroup'>;
}
declare module 'vuetify/src/components/lists/ListTile.js' {
  declare module.exports: $Exports<'vuetify/src/components/lists/ListTile'>;
}
declare module 'vuetify/src/components/lists/ListTile.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/lists/ListTile.spec'>;
}
declare module 'vuetify/src/components/lists/ListTileAction.js' {
  declare module.exports: $Exports<'vuetify/src/components/lists/ListTileAction'>;
}
declare module 'vuetify/src/components/menus/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/menus/index'>;
}
declare module 'vuetify/src/components/menus/Menu.js' {
  declare module.exports: $Exports<'vuetify/src/components/menus/Menu'>;
}
declare module 'vuetify/src/components/menus/Menu.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/menus/Menu.spec'>;
}
declare module 'vuetify/src/components/menus/mixins/activator.js' {
  declare module.exports: $Exports<'vuetify/src/components/menus/mixins/activator'>;
}
declare module 'vuetify/src/components/menus/mixins/generators.js' {
  declare module.exports: $Exports<'vuetify/src/components/menus/mixins/generators'>;
}
declare module 'vuetify/src/components/menus/mixins/keyable.js' {
  declare module.exports: $Exports<'vuetify/src/components/menus/mixins/keyable'>;
}
declare module 'vuetify/src/components/menus/mixins/position.js' {
  declare module.exports: $Exports<'vuetify/src/components/menus/mixins/position'>;
}
declare module 'vuetify/src/components/menus/mixins/utils.js' {
  declare module.exports: $Exports<'vuetify/src/components/menus/mixins/utils'>;
}
declare module 'vuetify/src/components/navigation-drawer/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/navigation-drawer/index'>;
}
declare module 'vuetify/src/components/navigation-drawer/NavigationDrawer.js' {
  declare module.exports: $Exports<'vuetify/src/components/navigation-drawer/NavigationDrawer'>;
}
declare module 'vuetify/src/components/pagination/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/pagination/index'>;
}
declare module 'vuetify/src/components/pagination/Pagination.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/pagination/Pagination.spec'>;
}
declare module 'vuetify/src/components/parallax/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/parallax/index'>;
}
declare module 'vuetify/src/components/parallax/Parallax.js' {
  declare module.exports: $Exports<'vuetify/src/components/parallax/Parallax'>;
}
declare module 'vuetify/src/components/pickers/DatePicker.js' {
  declare module.exports: $Exports<'vuetify/src/components/pickers/DatePicker'>;
}
declare module 'vuetify/src/components/pickers/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/pickers/index'>;
}
declare module 'vuetify/src/components/pickers/mixins/date-header.js' {
  declare module.exports: $Exports<'vuetify/src/components/pickers/mixins/date-header'>;
}
declare module 'vuetify/src/components/pickers/mixins/date-table.js' {
  declare module.exports: $Exports<'vuetify/src/components/pickers/mixins/date-table'>;
}
declare module 'vuetify/src/components/pickers/mixins/date-title.js' {
  declare module.exports: $Exports<'vuetify/src/components/pickers/mixins/date-title'>;
}
declare module 'vuetify/src/components/pickers/mixins/date-years.js' {
  declare module.exports: $Exports<'vuetify/src/components/pickers/mixins/date-years'>;
}
declare module 'vuetify/src/components/pickers/mixins/time-body.js' {
  declare module.exports: $Exports<'vuetify/src/components/pickers/mixins/time-body'>;
}
declare module 'vuetify/src/components/pickers/mixins/time-title.js' {
  declare module.exports: $Exports<'vuetify/src/components/pickers/mixins/time-title'>;
}
declare module 'vuetify/src/components/pickers/TimePicker.js' {
  declare module.exports: $Exports<'vuetify/src/components/pickers/TimePicker'>;
}
declare module 'vuetify/src/components/pickers/TimePicker.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/pickers/TimePicker.spec'>;
}
declare module 'vuetify/src/components/progress/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/progress/index'>;
}
declare module 'vuetify/src/components/selection-controls/Checkbox.js' {
  declare module.exports: $Exports<'vuetify/src/components/selection-controls/Checkbox'>;
}
declare module 'vuetify/src/components/selection-controls/Checkbox.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/selection-controls/Checkbox.spec'>;
}
declare module 'vuetify/src/components/selection-controls/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/selection-controls/index'>;
}
declare module 'vuetify/src/components/selection-controls/Radio.js' {
  declare module.exports: $Exports<'vuetify/src/components/selection-controls/Radio'>;
}
declare module 'vuetify/src/components/selection-controls/Switch.js' {
  declare module.exports: $Exports<'vuetify/src/components/selection-controls/Switch'>;
}
declare module 'vuetify/src/components/selects/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/selects/index'>;
}
declare module 'vuetify/src/components/selects/mixins/autocomplete.js' {
  declare module.exports: $Exports<'vuetify/src/components/selects/mixins/autocomplete'>;
}
declare module 'vuetify/src/components/selects/mixins/generators.js' {
  declare module.exports: $Exports<'vuetify/src/components/selects/mixins/generators'>;
}
declare module 'vuetify/src/components/selects/Select.js' {
  declare module.exports: $Exports<'vuetify/src/components/selects/Select'>;
}
declare module 'vuetify/src/components/sliders/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/sliders/index'>;
}
declare module 'vuetify/src/components/sliders/Slider.js' {
  declare module.exports: $Exports<'vuetify/src/components/sliders/Slider'>;
}
declare module 'vuetify/src/components/snackbars/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/snackbars/index'>;
}
declare module 'vuetify/src/components/snackbars/Snackbar.js' {
  declare module.exports: $Exports<'vuetify/src/components/snackbars/Snackbar'>;
}
declare module 'vuetify/src/components/snackbars/Snackbar.spec.js' {
  declare module.exports: $Exports<'vuetify/src/components/snackbars/Snackbar.spec'>;
}
declare module 'vuetify/src/components/steppers/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/steppers/index'>;
}
declare module 'vuetify/src/components/steppers/Stepper.js' {
  declare module.exports: $Exports<'vuetify/src/components/steppers/Stepper'>;
}
declare module 'vuetify/src/components/steppers/StepperContent.js' {
  declare module.exports: $Exports<'vuetify/src/components/steppers/StepperContent'>;
}
declare module 'vuetify/src/components/steppers/StepperStep.js' {
  declare module.exports: $Exports<'vuetify/src/components/steppers/StepperStep'>;
}
declare module 'vuetify/src/components/subheaders/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/subheaders/index'>;
}
declare module 'vuetify/src/components/subheaders/Subheader.js' {
  declare module.exports: $Exports<'vuetify/src/components/subheaders/Subheader'>;
}
declare module 'vuetify/src/components/tables/DataTable.js' {
  declare module.exports: $Exports<'vuetify/src/components/tables/DataTable'>;
}
declare module 'vuetify/src/components/tables/EditDialog.js' {
  declare module.exports: $Exports<'vuetify/src/components/tables/EditDialog'>;
}
declare module 'vuetify/src/components/tables/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/tables/index'>;
}
declare module 'vuetify/src/components/tables/mixins/body.js' {
  declare module.exports: $Exports<'vuetify/src/components/tables/mixins/body'>;
}
declare module 'vuetify/src/components/tables/mixins/foot.js' {
  declare module.exports: $Exports<'vuetify/src/components/tables/mixins/foot'>;
}
declare module 'vuetify/src/components/tables/mixins/head.js' {
  declare module.exports: $Exports<'vuetify/src/components/tables/mixins/head'>;
}
declare module 'vuetify/src/components/tables/mixins/progress.js' {
  declare module.exports: $Exports<'vuetify/src/components/tables/mixins/progress'>;
}
declare module 'vuetify/src/components/tabs/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/tabs/index'>;
}
declare module 'vuetify/src/components/tabs/Tabs.js' {
  declare module.exports: $Exports<'vuetify/src/components/tabs/Tabs'>;
}
declare module 'vuetify/src/components/tabs/TabsBar.js' {
  declare module.exports: $Exports<'vuetify/src/components/tabs/TabsBar'>;
}
declare module 'vuetify/src/components/tabs/TabsContent.js' {
  declare module.exports: $Exports<'vuetify/src/components/tabs/TabsContent'>;
}
declare module 'vuetify/src/components/tabs/TabsItem.js' {
  declare module.exports: $Exports<'vuetify/src/components/tabs/TabsItem'>;
}
declare module 'vuetify/src/components/text-fields/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/text-fields/index'>;
}
declare module 'vuetify/src/components/text-fields/TextField.js' {
  declare module.exports: $Exports<'vuetify/src/components/text-fields/TextField'>;
}
declare module 'vuetify/src/components/toolbar/index.js' {
  declare module.exports: $Exports<'vuetify/src/components/toolbar/index'>;
}
declare module 'vuetify/src/components/toolbar/SystemBar.js' {
  declare module.exports: $Exports<'vuetify/src/components/toolbar/SystemBar'>;
}
declare module 'vuetify/src/components/toolbar/Toolbar.js' {
  declare module.exports: $Exports<'vuetify/src/components/toolbar/Toolbar'>;
}
declare module 'vuetify/src/components/toolbar/ToolbarSideIcon.js' {
  declare module.exports: $Exports<'vuetify/src/components/toolbar/ToolbarSideIcon'>;
}
declare module 'vuetify/src/components/transitions/_index.js' {
  declare module.exports: $Exports<'vuetify/src/components/transitions/_index'>;
}
declare module 'vuetify/src/directives/_index.js' {
  declare module.exports: $Exports<'vuetify/src/directives/_index'>;
}
declare module 'vuetify/src/directives/badge.js' {
  declare module.exports: $Exports<'vuetify/src/directives/badge'>;
}
declare module 'vuetify/src/directives/click-outside.js' {
  declare module.exports: $Exports<'vuetify/src/directives/click-outside'>;
}
declare module 'vuetify/src/directives/ripple.js' {
  declare module.exports: $Exports<'vuetify/src/directives/ripple'>;
}
declare module 'vuetify/src/directives/tooltip.js' {
  declare module.exports: $Exports<'vuetify/src/directives/tooltip'>;
}
declare module 'vuetify/src/index.js' {
  declare module.exports: $Exports<'vuetify/src/index'>;
}
declare module 'vuetify/src/mixins/bootable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/bootable'>;
}
declare module 'vuetify/src/mixins/colorable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/colorable'>;
}
declare module 'vuetify/src/mixins/contextualable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/contextualable'>;
}
declare module 'vuetify/src/mixins/detachable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/detachable'>;
}
declare module 'vuetify/src/mixins/expand-transition.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/expand-transition'>;
}
declare module 'vuetify/src/mixins/filterable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/filterable'>;
}
declare module 'vuetify/src/mixins/input.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/input'>;
}
declare module 'vuetify/src/mixins/overlayable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/overlayable'>;
}
declare module 'vuetify/src/mixins/picker.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/picker'>;
}
declare module 'vuetify/src/mixins/positionable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/positionable'>;
}
declare module 'vuetify/src/mixins/resizable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/resizable'>;
}
declare module 'vuetify/src/mixins/route-link.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/route-link'>;
}
declare module 'vuetify/src/mixins/selectable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/selectable'>;
}
declare module 'vuetify/src/mixins/swipeable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/swipeable'>;
}
declare module 'vuetify/src/mixins/themeable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/themeable'>;
}
declare module 'vuetify/src/mixins/toggleable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/toggleable'>;
}
declare module 'vuetify/src/mixins/transitionable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/transitionable'>;
}
declare module 'vuetify/src/mixins/translatable.js' {
  declare module.exports: $Exports<'vuetify/src/mixins/translatable'>;
}
declare module 'vuetify/src/util/helpers.js' {
  declare module.exports: $Exports<'vuetify/src/util/helpers'>;
}
declare module 'vuetify/src/util/load.js' {
  declare module.exports: $Exports<'vuetify/src/util/load'>;
}
declare module 'vuetify/src/util/testing.js' {
  declare module.exports: $Exports<'vuetify/src/util/testing'>;
}
declare module 'vuetify/src/util/touch.js' {
  declare module.exports: $Exports<'vuetify/src/util/touch'>;
}
